In [1]:
import sys
sys.path.append("../src")

from data_cleaning import load_trader_data, load_sentiment_data
from feature_engineering import merge_data, create_features
from visualization import save_pnl_by_sentiment, save_winrate_by_sentiment, save_volume_by_sentiment

import pandas as pd

In [2]:
trader_df = load_trader_data("../data/raw/historical_data.csv")
sentiment_df = load_sentiment_data("../data/raw/fear_greed_index.csv")

trader_df.head()

,account,coin,execution_price,size,usd_value,side,time,start_position,event,closed_pnl,hash,order_id,crossed,fee,trade_id,timestamp,date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02

In [3]:
merged_df = merge_data(trader_df, sentiment_df)
merged_df = create_features(merged_df)

merged_df.head()

,account,coin,execution_price,size,usd_value,side,time,start_position,event,closed_pnl,...,trade_id,timestamp,date,sentiment_value,market_sentiment,is_profitable,loss_trade,trade_direction,pnl_per_usd,fee_ratio
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,buy,0.0,...,8.950000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False,False,BUY,0.0,0.000044
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,buy,0.0,...,4.430000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False,False,BUY,0.0,0.000044
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,buy,0.0,...,6.600000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False,False,BUY,0.0,0.000044
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,buy,0.0,...,1.080000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed,False,False,BUY,0.0,0.000044
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,buy,0.0,...,1.050000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed,False,False,BUY,0.0,0.000044

In [4]:
merged_df.isnull().sum()

account             0
coin                0
execution_price     0
size                0
usd_value           0
side                0
time                0
start_position      0
event               0
closed_pnl          0
hash                0
order_id            0
crossed             0
fee                 0
trade_id            0
timestamp           0
date                0
sentiment_value     0
market_sentiment    0
is_profitable       0
loss_trade          0
trade_direction     0
pnl_per_usd         0
fee_ratio           0
dtype: int64

In [5]:
print("Rows and Columns:", merged_df.shape)

Rows and Columns: (211224, 24)

In [6]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   account           211224 non-null  str
 1   coin              211224 non-null  str
 2   execution_price   211224 non-null  float64
 3   size              211224 non-null  float64
 4   usd_value         211224 non-null  float64
 5   side              211224 non-null  str
 6   time              211224 non-null  datetime64[us]
 7   start_position    211224 non-null  float64
 8   event             211224 non-null  str
 9   closed_pnl        211224 non-null  float64
 10  hash              211224 non-null  str
 11  order_id          211224 non-null  int64
 12  crossed           211224 non-null  bool
 13  fee               211224 non-null  float64
 14  trade_id          211224 non-null  float64
 15  timestamp         211224 non-null  float64
 16  date              211224 non-null  object
 17  sentiment_value   211224 non-null  float64
 18  market_sentiment  211224 non-null  str
 19  is_profitable     211224 non-null  bool
 20  loss_trade        211224 non-null  bool
 21  trade_direction   211224 non-null  str
 22  pnl_per_usd       211224 non-null  float64
 23  fee_ratio         211224 non-null  float64
dtypes: bool(3), datetime64[us](1), float64(11), int64(1), object(1), str(7)
memory usage: 34.4+ MB

In [7]:
merged_df.describe()

,execution_price,size,usd_value,time,start_position,closed_pnl,order_id,fee,trade_id,timestamp,sentiment_value,pnl_per_usd,fee_ratio
count,211224.000000,2.112240e+05,2.112240e+05,211224,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05,211224.000000,211224.000000,211224.000000
mean,11414.723350,4.623365e+03,5.639451e+03,2025-01-31 12:04:22.915010,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12,51.648189,0.018991,0.000349
min,0.000005,8.740000e-07,0.000000e+00,2023-05-01 01:06:00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12,0.000000,-384.406426,-0.000020
25%,4.854700,2.940000e+00,1.937900e+02,2024-12-31 21:00:45,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12,33.000000,0.000000,0.000096
50%,18.280000,3.200000e+01,5.970450e+02,2025-02-24 18:55:00,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12,49.000000,0.000000,0.000250
75%,101.580000,1.879025e+02,2.058960e+03,2025-04-02 18:22:00,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12,72.000000,0.010318,0.000350
max,109004.000000,1.582244e+07,3.921431e+06,2025-05-01 12:13:00,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12,94.000000,3.403550,1.432547
std,29447.654868,1.042729e+05,3.657514e+04,NaN,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09,21.014288,0.845727,0.009503

In [8]:
merged_df["market_sentiment"].value_counts()

market_sentiment
Fear             61837
Greed            50303
Extreme Greed    39992
Neutral          37686
Extreme Fear     21400
Unknown              6
Name: count, dtype: int64

In [9]:
print("Total PnL:", merged_df["closed_pnl"].sum())

Total PnL: 10296958.943436

In [10]:
print("Average PnL:", merged_df["closed_pnl"].mean())

Average PnL: 48.74900079269401

In [11]:
sentiment_summary = merged_df.groupby("market_sentiment").agg(
    total_trades=("account", "count"),
    total_volume=("usd_value", "sum"),
    avg_pnl=("closed_pnl", "mean"),
    total_pnl=("closed_pnl", "sum"),
    win_rate=("is_profitable", "mean"),
    avg_fee=("fee", "mean")
).reset_index()

sentiment_summary

,market_sentiment,total_trades,total_volume,avg_pnl,total_pnl,win_rate,avg_fee
0,Extreme Fear,21400,1.144843e+08,34.537862,7.391102e+05,0.370607,1.116291
1,Extreme Greed,39992,1.244652e+08,67.892861,2.715171e+06,0.464943,0.675902
2,Fear,61837,4.833248e+08,54.290400,3.357155e+06,0.420768,1.495172
3,Greed,50303,2.885825e+08,42.743559,2.150129e+06,0.384828,1.254372
4,Neutral,37686,1.802421e+08,34.307718,1.292921e+06,0.396991,1.044798
5,Unknown,6,8.866886e+04,7078.665688,4.247199e+04,1.000000,1.418701

In [12]:
side_summary = merged_df.groupby(
    ["market_sentiment", "side"]
).agg(
    total_trades=("account", "count"),
    avg_pnl=("closed_pnl", "mean"),
    total_pnl=("closed_pnl", "sum"),
    win_rate=("is_profitable", "mean")
).reset_index()

side_summary

   market_sentiment  side  total_trades      avg_pnl     total_pnl  win_rate
0      Extreme Fear   BUY         10935    34.114627  3.730434e+05  0.201646
1      Extreme Fear  SELL         10465    34.980106  3.660668e+05  0.547157
2     Extreme Greed   BUY         17940    10.498927  1.883508e+05  0.311427
3     Extreme Greed  SELL         22052   114.584643  2.526821e+06  0.589833
4              Fear   BUY         30270    63.927104  1.935073e+06  0.263000
5              Fear  SELL         31567    45.049641  1.422082e+06  0.572053
6             Greed   BUY         24576    25.002302  6.144566e+05  0.318075
7             Greed  SELL         25727    59.691091  1.535673e+06  0.448595
8           Neutral   BUY         18969    29.227429  5.544151e+05  0.240023
9           Neutral  SELL         18717    39.456408  7.385056e+05  0.556072
10          Unknown   BUY             6  7078.665688  4.247199e+04  1.000000

In [13]:
top_traders = merged_df.groupby("account").agg(
    total_trades=("account", "count"),
    total_pnl=("closed_pnl", "sum"),
    avg_pnl=("closed_pnl", "mean"),
    win_rate=("is_profitable", "mean"),
    total_volume=("usd_value", "sum")
).reset_index()

top_traders = top_traders.sort_values(
    "total_pnl",
    ascending=False
)

top_traders.head(10)

,account,total_trades,total_pnl,avg_pnl,win_rate,total_volume
27,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,14733,2.143383e+06,145.481748,0.337134,5.654357e+07
0,0x083384f897ee0f19899168e3b1bec365f52a9012,3818,1.600230e+06,419.127768,0.359612,6.169726e+07
29,0xbaaaf6571ab7d571043ff1e313a9609a10637864,21192,9.401638e+05,44.364091,0.467582,6.803634e+07
13,0x513b8629fe877bb581bf244e326a047b249c4ff1,12236,8.404226e+05,68.684419,0.401193,4.208766e+08
31,0xbee1707d6b44d4d52bfe19e41f8a828645437aab,40184,8.360806e+05,20.806305,0.428230,7.410781e+07
11,0x4acb90e786d897ecffb614dc822eb231b4ffb9f4,4356,6.777471e+05,155.589314,0.486226,3.957295e+07
15,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,1590,4.293556e+05,270.034947,0.345912,1.147450e+07
9,0x430f09841d65beb3f27765503d0f850b8bce7713,1237,4.165419e+05,336.735548,0.484236,2.966109e+06
16,0x72c6a4624e1dffa724e6d00d64ceae698af892a0,1430,4.030115e+05,281.826227,0.306294,3.051144e+06
17,0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4,9893,3.790954e+05,38.319560,0.810876,2.572950e+07

In [14]:
top_traders.tail(10)

,account,total_trades,total_pnl,avg_pnl,win_rate,total_volume
7,0x3f9a0aadc7f04a7c9d75dc1b5a6ddd6e36486cf6,332,53496.247243,161.133275,0.475904,1.143896e+06
1,0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd,7280,47885.320514,6.577654,0.442720,1.203549e+07
21,0x8477e447846c758f5a675856001ea72298fd9cb5,14998,43917.008976,2.928191,0.261968,1.230479e+07
28,0xb899e522b5715391ae1d4f137653e7906c5e2115,4838,22488.500821,4.648305,0.438611,1.088770e+08
26,0xaf40fdc468c30116bd3307bcbf4a451a7ebf1deb,534,21758.831753,40.746876,0.322097,4.448323e+06
18,0x7f4f299f74eec87806a830e3caa9afa5f2b9db8f,1559,14900.443047,9.557693,0.452213,5.844484e+06
6,0x39cef799f8b69da1995852eea189df24eb5cae3c,3589,14456.919336,4.028119,0.327668,1.719338e+07
5,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,815,-31203.599986,-38.286626,0.455215,1.409902e+06
2,0x271b280974205ca63b716753467d5a371de622ab,3809,-70436.191318,-18.492043,0.301917,3.387344e+07
19,0x8170715b3b381dffb7062c0298972d4727a0a63b,4601,-167621.124781,-36.431455,0.382743,1.014376e+07

In [15]:
coin_summary = merged_df.groupby("coin").agg(
    total_trades=("coin", "count"),
    total_volume=("usd_value", "sum"),
    total_pnl=("closed_pnl", "sum")
).reset_index()

coin_summary.sort_values(
    "total_volume",
    ascending=False
).head(10)

         coin  total_trades  total_volume     total_pnl
105       BTC         26064  6.442321e+08  8.680447e+05
137      HYPE         68005  1.419902e+08  1.948485e+06
205       SOL         10691  1.250748e+08  1.639556e+06
120       ETH         11158  1.182810e+08  1.319979e+06
4        @107         29992  5.576086e+07  2.783913e+06
122  FARTCOIN          4650  8.311390e+06 -1.006872e+05
210       SUI          1979  7.781168e+06  1.992688e+05
217     TRUMP          1920  7.349347e+06 -3.648249e+05
161   MELANIA          4428  7.040710e+06  3.903511e+05
233       XRP          1774  5.343211e+06  3.756901e+03

In [16]:
save_pnl_by_sentiment(
    merged_df,
    "../visuals/pnl_by_sentiment.png"
)

save_winrate_by_sentiment(
    merged_df,
    "../visuals/winrate_by_sentiment.png"
)

save_volume_by_sentiment(
    merged_df,
    "../visuals/volume_by_sentiment.png"
)

print("Charts saved successfully")

Charts saved successfully

In [17]:
numeric_cols = [
    "execution_price",
    "size",
    "usd_value",
    "closed_pnl",
    "fee",
    "sentiment_value"
]

merged_df[numeric_cols].corr()

,execution_price,size,usd_value,closed_pnl,fee,sentiment_value
execution_price,1.000000,-0.017185,0.189855,-0.006505,0.225265,-0.027529
size,-0.017185,1.000000,0.013310,0.005068,0.006710,0.023077
usd_value,0.189855,0.013310,1.000000,0.123589,0.745939,-0.029858
closed_pnl,-0.006505,0.005068,0.123589,1.000000,0.084020,0.007575
fee,0.225265,0.006710,0.745939,0.084020,1.000000,-0.026878
sentiment_value,-0.027529,0.023077,-0.029858,0.007575,-0.026878,1.000000

In [18]:
merged_df.to_csv(
    "../data/processed/merged_trader_sentiment.csv",
    index=False
)

print("Processed dataset saved")

Processed dataset saved

In [19]:
print("""
KEY INSIGHTS:

1. Trader profitability changes with market sentiment.
2. Fear/Extreme Fear periods may create profitable opportunities.
3. Greed periods often show higher trading volume.
4. Buy and Sell performance differs across sentiments.
5. Some traders consistently outperform others.
6. Sentiment can help improve trading strategy decisions.
""")

KEY INSIGHTS:

1. Trader profitability changes with market sentiment.
2. Fear/Extreme Fear periods may create profitable opportunities.
3. Greed periods often show higher trading volume.
4. Buy and Sell performance differs across sentiments.
5. Some traders consistently outperform others.
6. Sentiment can help improve trading strategy decisions.